### ISSUE TITLE
"location.protocol" must be http or https and web storage must be enabled."

### ISSUE THREAD

**Issue by natashache** [JamesMarino/Firebase-ReactNative#4]
Hi @JamesMarino,

I'm following your code to set up my own react-native app with firebase. But I keep getting the error:
"This operation is not supported in the environment this application is running on. "location.protocol" must be http or https and web storage must be enabled."

Any idea what this is about? I tried googling it but couldn't find much. Thanks!

**Comment by JamesMarino** [comment]
Sorry @natashache I'm not too sure anymore as this article is out of date. I might update this article and code eventually but I'm now focused more on the infrastructure side of things rather than frontend.
